name: E2E tests

on: [push, pull_request]

jobs:
  parallel-runs-across-platforms:
    name: OS & Node matrixes
    strategy:
      matrix:
        os: ['ubuntu-latest'] #, 'windows-latest', 'macos-latest']
        machines: [1, 2]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout ${{ github.repository }} repository
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm 
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npx cypress run
        # timeout-minutes: 10
        # with:
        #   record: true
        #   parallel: true
        #   group: Parallel 2x on ${{ matrix.os }}
        #   # on Mac and Linux we can use "npm start"
        #   start: npx cypress run
        #   # but for this particular project on Windows we need a different start command
        #   start-windows: npm run start:ci:windows
        # env:
        #   # pass the Dashboard record key as an environment variable
        #   CYPRESS_RECORD_KEY: ${{ secrets.dashboardRecordKey }}