name: E2E tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machines: [1, 2, 3]
    #container: cypress/browsers:latest
    steps:
      - name: Checkout ${{ github.repository }} repository
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          browser: chrome
