name: E2E tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:latest
    steps:
      - name: Checkout ${{ github.repository }} repository
        uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
